# Use an official Node.js runtime as the base image
FROM node:20

# Set the working directory in the Docker image
WORKDIR /usr/src/app

# Copy package.json and yarn.lock to the working directory
COPY package.json yarn.lock ./

# Install the application's dependencies inside the Docker image
RUN yarn install

# Copy the rest of the application to the working directory
COPY . .

# Build the application for production
RUN yarn build

# Expose port 5173 for the application
EXPOSE 5173

# Define the command to run the application
CMD [ "yarn", "dev" ]